server:
  port: 8081

spring:
  application:
    name: user-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/user_hub
    # url: jdbc:mysql://localhost:3306/user_hub
    username: root
    password: Diego@2116
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
      # defaultZone: 'http://host.docker.internal:8761/eureka/'
  instance:
    prefer-ip-address: true
    hostname: user-service
